# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-05-15 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_tb',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('passw', models.CharField(max_length=30)),
                ('usertype', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='maker_tb',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('p_lid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('licence', models.IntegerField()),
                ('contact', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=15)),
                ('passw', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('o_lid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('typ', models.CharField(max_length=15)),
                ('status', models.CharField(max_length=15)),
                ('rate', models.CharField(max_length=7)),
                ('track', models.CharField(max_length=15)),
                ('address', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='phar_tb',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('p_lid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=15)),
                ('passw', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='register',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('users', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('sold', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('s_lid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('des', models.TextField(max_length=120)),
                ('typ', models.CharField(max_length=15)),
                ('rate', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='user_tb',
            fields=[
                ('lid', models.IntegerField(primary_key=True, serialize=False)),
                ('u_lid', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('place', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=7)),
                ('date', models.DateField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=15)),
                ('passw', models.CharField(max_length=30)),
                ('add', models.TextField(max_length=130)),
            ],
        ),
    ]
